# Generated by Django 5.1 on 2026-03-17 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0030_warnings_handle_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='p_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Nurse_Record',
            fields=[
                ('nr_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('blood_type', models.CharField(max_length=5, null=True)),
                ('blood_rh', models.CharField(max_length=5, null=True)),
                ('hbv', models.IntegerField(default=0)),
                ('hcv', models.IntegerField(default=0)),
                ('hiv', models.IntegerField(default=0)),
                ('a_p', models.TextField(null=True)),
                ('constraint', models.TextField(null=True)),
                ('fall_risk', models.TextField(null=True)),
                ('fiber_list', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('medical_order', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.dialysis')),
            ],
            options={
                'db_table': 'nurse_record',
            },
        ),
    ]
